version: 2

sources:
    - name: raw
      description: This is a replica of the Postgres database used by our app
      database: postgres
      schema: kaggle
      tables:
          - name: machines
            description: maquinas
          - name: errors
            description: errors
          - name: failures
            description: falhas
          - name: maint
            description: falhas
          - name: telemetry
            description: telemetria